server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://dpg-d75802gule4c73ffmo20-a:5432/fintrack_db_3q7n


spring.datasource.username=fintrack_db_3q7n_user
spring.datasource.password=BQXzIC62zUqzFGVhElVZOdtPubSGpLlh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration (in production, use environment variables and a strong secret key)
fintrack.app.jwtSecret=SuperSecretKeyForFinTrackAppWhichNeedsToBeAtLeast32BytesLongForHS256Algorithm
fintrack.app.jwtExpirationMs=86400000

# CORS settings
app.cors.allowedOrigins=*
