server.port=${PORT:8081}

spring.datasource.url=jdbc:postgresql://localhost:5434/fintrackdb

spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration (in production, use environment variables and a strong secret key)
fintrack.app.jwtSecret=SuperSecretKeyForFinTrackAppWhichNeedsToBeAtLeast32BytesLongForHS256Algorithm
fintrack.app.jwtExpirationMs=86400000

# CORS settings
app.cors.allowedOrigins=http://localhost:5173
